### ISSUE TITLE
Dependency composer problem

### ISSUE THREAD

**Issue by jsamouh** [ddeboer/DdeboerSalesforceMapperBundle#12]
"ddeboer/salesforce-mapper-bundle": "*"
## composer update

Problem 1
    - ddeboer/salesforce-client-bundle 0.1.1 requires besimple/soap-bundle \* -> no matching package found.
    - ddeboer/salesforce-client-bundle 0.1 requires besimple/soap-bundle \* -> no matching package found.
    - symfony/framework-standard-edition 2.3.x-dev requires ddeboer/salesforce-mapper-bundle \* -> satisfiable by ddeboer/salesforce-mapper-bundle[0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6].
    - ddeboer/salesforce-mapper-bundle 0.1 requires ddeboer/salesforce-client-bundle \* -> satisfiable by ddeboer/salesforce-client-bundle[0.1, 0.1.1].
    - ddeboer/salesforce-mapper-bundle 0.1.1 requires ddeboer/salesforce-client-bundle \* -> satisfiable by ddeboer/salesforce-client-bundle[0.1, 0.1.1].
    - ddeboer/salesforce-mapper-bundle 0.1.2 requires ddeboer/salesforce-client-bundle \* -> satisfiable by ddeboer/salesforce-client-bundle[0.1, 0.1.1].
    - ddeboer/salesforce-mapper-bundle 0.1.3 requires ddeboer/salesforce-client-bundle \* -> satisfiable by ddeboer/salesforce-client-bundle[0.1, 0.1.1].
    - ddeboer/salesforce-mapper-bundle 0.1.4 requires ddeboer/salesforce-client-bundle \* -> satisfiable by ddeboer/salesforce-client-bundle[0.1, 0.1.1].
    - ddeboer/salesforce-mapper-bundle 0.1.5 requires ddeboer/salesforce-client-bundle \* -> satisfiable by ddeboer/salesforce-client-bundle[0.1, 0.1.1].
    - ddeboer/salesforce-mapper-bundle 0.1.6 requires ddeboer/salesforce-client-bundle \* -> satisfiable by ddeboer/salesforce-client-bundle[0.1, 0.1.1].
    - Installation request for symfony/framework-standard-edition 2.3.x-dev -> satisfiable by symfony/framework-standard-edition[2.3.x-dev].

**Comment by ddeboer** [comment]
This was [solved in master](https://github.com/ddeboer/DdeboerSalesforceMapperBundle/commit/9023e64cee9accd19c61d54e515334865d8a1fc5), but hadn't yet been tagged. I just did: please try to reinstall the bundle (version 0.2.0).
