### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by gabma** [ddeboer/DdeboerSalesforceMapperBundle#15]
Hi,

I'm trying to load your bundle but I'm getting an error when loading it in app kernel

FatalErrorException: Compile Error: Declaration of Ddeboer\Salesforce\MapperBundle\Request\ParamConverter\SalesforceParamConverter::apply() must be compatible with Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\ParamConverterInterface::apply(Symfony\Component\HttpFoundation\Request $request, Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter $configuration) in /path/vendor/ddeboer/salesforce-mapper-bundle/Ddeboer/Salesforce/MapperBundle/Request/ParamConverter/SalesforceParamConverter.php line 18

Imcompatible version maybe? I'm running symfony 2.5

**Comment by ddeboer** [comment]
Please use https://github.com/phpforce/salesforce-bundle instead.
