### ISSUE TITLE
Creating queries through mapper findOneBy

### ISSUE THREAD

**Issue by legetz** [ddeboer/DdeboerSalesforceMapperBundle#3]
First of all, thanks for the nice bundle :)

I found a bug from findOneBy (at least) method:
1. Call it by providing array with the key which datatype is not a string in SF ( like Number(18, 0) )
2. It returns error: value of filter criterion for field 'Myfield__c' must be of type double and should not be enclosed in quotes
3. Query looks like this: SELECT from MyObject__c where Myfield__c = '1'
4. Correct one should be: SELECT from MyObject__c where Myfield__c = 1

It would be nice if I could determine datatype with using annotation at model class?

**Comment by ddeboer** [comment]
@legetz Thank you for your report. Thanks to @timo-p, the issue has been resolved. 

It's very nice to see that people are using the bundle, and even contributing to it!

In an early version of the bundle, I did exactly what you propose: use the annotations to specify data types for the fields on the Salesforce objects. Now, however, I use Salesforce's describe calls to automatically determine the data types. Saves you from writing annotations. ;)
